<?php

$key = 'fppweb2024dapunta';

function getIncrement() {
    global $key;
    $increment = 0;
    for ($i = 0; $i < strlen($key); $i++) {$increment += ord($key[$i]);}
    return $increment;
}

function decrypt($string) {
    $increment = getIncrement();
    $raw = urldecode(base64_decode($string));
    $result = '';
    for ($i = 0; $i < mb_strlen($raw, 'UTF-8'); $i++) {$result .= mb_chr(mb_ord(mb_substr($raw, $i, 1), 'UTF-8') - $increment, 'UTF-8');}
    return $result;
}

function decryptorPayload($string) {
    $raw = urldecode(base64_decode($string));
    $rew = explode('|', $raw);
    $decryptedPayload = decrypt($rew[0]);
    $payload = json_decode($decryptedPayload, true);
    $ip = decrypt($rew[1]);
    $timestamp = intval(decrypt($rew[2]));

    print_r($payload);
    echo "IP: $ip\n";
    echo "Timestamp: $timestamp\n";
}

$enc_string = 'SlVSQkpVSTBKVVE1SlRsQ0pVUkJKVUU1SlVSQkpUbEZKVVJCSlVGREpVUkJKVGxCSlVSQkpVRTNKVVJCSlRsQkpVUkJKVUUzSlVRNUpUbENKVVE1SlVJekpVUkJKVUkwSlVRNUpUbENKVVJCSlRoQ0pVUTVKVUpFSlVSQkpUZ3dKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVGQkpVUTVKVGxDSlVRNUpVSXpKVVJCSlVJMEpVUTVKVGxDSlVSQkpUbERKVVJCSlVFNEpVUkJKVUZGSlVSQkpVRTNKVVJCSlVGRUpVUTVKVGxDSlVRNUpVSXpKVVE1SlVGQkpVUTVKVUUxSlVRNUpUbENKVVJCSlVFNUpVUkJKVUZDSlVSQkpVRXlKVVJCSlRsREpVUkJKVGxGSlVRNUpUbENKVVE1SlVJekpVUTVKVUZDSlVRNUpVSXhKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVJCSlVJMkpVUTVKVUUxSlVRNUpUbENKVVJCSlRoQ0pVUkJKVGt3SlVSQkpUZzNKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVGQ0pVUTVKVGxDSlVRNUpVSXpKVVJCSlVJMEpVUTVKVGxDSlVSQkpUbERKVVJCSlVFNEpVUkJKVUZGSlVSQkpVRTNKVVJCSlVGRUpVUTVKVGxDSlVRNUpVSXpKVVE1SlVGQ0pVUTVKVUUxSlVRNUpUbENKVVJCSlVFNUpVUkJKVUZDSlVSQkpVRXlKVVJCSlRsREpVUkJKVGxGSlVRNUpUbENKVVE1SlVJekpVUTVKVUZESlVRNUpVRkNKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVJCSlVJMkpVUTVKVUUxSlVRNUpUbENKVVJCSlRoREpVUkJKVGhFSlVSQkpUZzBKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVE1SlVGREpVUTVKVGxDSlVRNUpVSXpKVVJCSlVJMEpVUTVKVGxDSlVSQkpUbERKVVJCSlVFNEpVUkJKVUZGSlVSQkpVRTNKVVJCSlVGRUpVUTVKVGxDSlVRNUpVSXpKVVE1SlVGQ0pVUTVKVUUxSlVRNUpUbENKVVJCSlVFNUpVUkJKVUZDSlVSQkpVRXlKVVJCSlRsREpVUkJKVGxGSlVRNUpUbENKVVE1SlVJekpVUTVKVUZESlVRNUpVRkdKVVE1SlVFNUpVUTVKVUU1SlVRNUpVRTVKVVJCSlVJMkpVUkJKVUkySlVRNUpVRTFKVVE1SlRsQ0pVUkJKVUUySlVSQkpUbEZKVVJCSlVFekpVUkJKVGxCSlVRNUpUbENKVVE1SlVJekpVUTVKVGxDSlVRNUpVSkJKVVE1SlVGRUpVUTVKVGxDSlVRNUpVRTFKVVE1SlRsQ0pVUkJKVUU1SlVSQkpUbEJKVVJCSlVJeUpVUkJKVUUySlVSQkpUbEZKVVJCSlVFM0pVUkJKVUZFSlVRNUpUbENKVVE1SlVJekpVUTVKVGxDSlVRNUpVSkNKVVJCSlRreUpVUkJKVGhDSlVRNUpVRTVKVVE1SlVGQkpVUTVKVGxDSlVSQkpVSTIlN0NKVVE1SlVGQkpVUTVKVUl4SlVRNUpVRkNKVVE1SlVFM0pVUTVKVUZCSlVRNUpVRTNKVVE1SlVJeUpVUTVKVUl4SlVRNUpVRTNKVVE1SlVGQ0pVUTVKVUZESlVRNUpVRkIlN0NKVVE1SlVGQkpVUTVKVUl3SlVRNUpVRkRKVVE1SlVGQ0pVUTVKVUl5SlVRNUpVSXhKVVE1SlVJeEpVUTVKVUZFSlVRNUpVSXdKVVE1SlVGRg';

decryptorPayload($enc_string);